#ifndef __DRIVER_H
#define __DRIVER_H

#include <linux/ioctl.h> /* needed for the _IOW etc stuff used later */

#define DRIVER_IOC_MAGIC  'k'
#define DRIVER_IOCRESET    _IO(DRIVER_IOC_MAGIC, 0)
#define DRIVER_IOCSQUANTUM _IOW(DRIVER_IOC_MAGIC,  1, int)
#define DRIVER_IOCSQSET    _IOW(DRIVER_IOC_MAGIC,  2, int)
#define DRIVER_IOCTQUANTUM _IO(DRIVER_IOC_MAGIC,   3)
#define DRIVER_IOCTQSET    _IO(DRIVER_IOC_MAGIC,   4)
#define DRIVER_IOCGQUANTUM _IOR(DRIVER_IOC_MAGIC,  5, int)
#define DRIVER_IOCGQSET    _IOR(DRIVER_IOC_MAGIC,  6, int)
#define DRIVER_IOCQQUANTUM _IO(DRIVER_IOC_MAGIC,   7)
#define DRIVER_IOCQQSET    _IO(DRIVER_IOC_MAGIC,   8)
#define DRIVER_IOCXQUANTUM _IOWR(DRIVER_IOC_MAGIC, 9, int)
#define DRIVER_IOCXQSET    _IOWR(DRIVER_IOC_MAGIC,10, int)
#define DRIVER_IOCHQUANTUM _IO(DRIVER_IOC_MAGIC,  11)
#define DRIVER_IOCHQSET    _IO(DRIVER_IOC_MAGIC,  12)
#define DRIVER_IOC_MAXNR 12

#endif
